---
title: "Community Composition"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shinydashboard)
library(microbiome)
library(phyloseq)
library(DT)
library(ggplot2)
library(plotly)
library(knitr)
library(dplyr)
library(ggpubr)
library(hrbrthemes)
library(reshape2)
library(DirichletMultinomial)
library(vegan)
```
```{r, echo=FALSE}
datasetSubsetInputCode1()
```
```{r, echo=FALSE}
datasetSubsetInputCode2()
```
```{r, echo=FALSE}
datasetSubsetInputCode3()
```
```{r, echo=FALSE}
datasetSubsetInputCode4()
```
```{r, echo=FALSE}
datasetSubsetInputCode5()
```

```{r phylosummary, echo=FALSE}
if (input$renderSampleAbundancePlot == "Yes"){
  communityPlotParams()
}
```
```{r, echo=FALSE}
if (input$renderSampleAbundancePlot == "Yes"){
  communityPlotCodeParams1()
}
```
```{r, echo=FALSE}
if (input$renderSampleAbundancePlot == "Yes"){
  communityPlotCodeParams2()
}
```
```{r, echo=FALSE}
if (input$renderSampleAbundancePlot == "Yes"){
  communityPlotCodeParams3()
}
```
```{r taxasum, echo=FALSE}
if( input$renderRelativeAbundancePlot == "Yes"){
  communityPlotGenusParams()
}
```
```{r, echo=FALSE}
if( input$renderRelativeAbundancePlot == "Yes"){
  communityPlotGenusCodeParams()
}
```

```{r corelineplot, echo=FALSE}
if(input$renderAveragedRelativeAbundancePlot == "Yes"){
  communityBarplotParams()
}
```
```{r, echo=FALSE}
if(input$renderAveragedRelativeAbundancePlot == "Yes"){
  communityBarplotCodeParams1()
}
```
```{r, echo=FALSE}
if(input$renderAveragedRelativeAbundancePlot == "Yes"){
  communityBarplotCodeParams2()
}
```


```{r taxaplot, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceParams()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams1()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams2()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams3()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams4()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams5()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams6()
}
```
```{r, echo=FALSE}
if(input$renderPrevalencePlot == "Yes"){
  communityPrevalenceCodeParams7()
}
```