---
title: "Community Landscape"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shinydashboard)
library(microbiome)
library(phyloseq)
library(DT)
library(ggplot2)
library(plotly)
library(knitr)
library(dplyr)
library(ggpubr)
library(hrbrthemes)
library(reshape2)
library(DirichletMultinomial)
library(vegan)
```


```{r pca, echo=FALSE}
if (input$renderPCA == "Yes"){
  landscapePCAParams()
}
```
```{r, echo=FALSE}
if (input$renderPCA == "Yes"){
  landscapePCACodeParams()
}
```
```{r pcoamds, echo=FALSE}
if( input$renderPCOAMDS == "Yes"){
  landscapeOrdinationParams()
}
```
```{r, echo=FALSE}
if( input$renderPCOAMDS == "Yes"){
  landscapeOrdinationCodeParams()
}
```
```{r tsne, echo=FALSE}
if(input$renderTSNE == "Yes"){
  landscapeTSneParams()
}
```
```{r nmds, echo=FALSE}
if(input$renderTSNE == "Yes"){
  landscapeTSneCodeParams()
}
```
```{r count, echo=FALSE}
if(input$renderAbundanceHistograms == "Yes"){
  landscapeAbundanceHistAbsParams()
}
```
```{r, echo=FALSE}
if(input$renderAbundanceHistograms == "Yes"){
  landscapeAbundanceHistAbsCodeParams()
}
```
```{r abundance, echo=FALSE}
if(input$renderAbundanceHistograms == "Yes"){
  landscapeAbundanceHistRelParams()
}
```
```{r, echo=FALSE}
if(input$renderAbundanceHistograms == "Yes"){
  landscapeAbundanceHistRelCodeParams()
}
```

